resources:
  - name: gitrepo_res
    type: gitRepo
    repoPath: bharath92/samplePyt
    configuration:
      integrationName: bharath_github
      shallowDepth: 11
      gitConfig:
        - --global core.editor emacs
        - --global help.autocorrect 1
      buildOn:
        commit: true
        pullRequest: true
        pullRequestClose: true
        release: true
        tagPush: true
    initialVersion:
      sha: master
  - name: gitrepo_res2
    type: gitRepo
    repoPath: bharath92/api
    configuration:
      integrationName: bharath_github
    initialVersion:
      sha: master
  - name: admiralRepo
    type: gitRepo
    repoPath: bharath92/admiral
    configuration:
      integrationName: bharath_github
      shallowDepth: 11
      gitConfig:
        - --global core.editor vim
        - --global help.autocorrect 0
      buildOn:
        commit: true
        pullRequest: true
        pullRequestClose: true
        release: true
        tagPush: true
    initialVersion:
      sha: master
  - name: reqproc_repo
    type: gitRepo
    repoPath: bharath92/kermit-reqproc
    configuration:
      integrationName: bharath_github
    initialVersion:
      sha: master
  - name: reqproc_img
    type: image
    configuration:
      integrationName: docker
    imageName: bharath92/gitIssues
    initialVersion:
      imageTag: master


pipelines:
  - name: pipe_1
    setup:
      #environmentVariables:
      #  readOnly:
      #    readonlyfoo: readonlybar
      runtime:
        type: image
        image:
          custom:
            name: drydock/u16microbase
            tag: v7.2.4

    steps:
      - name: basic
        type: bash
        requires:
          integrations:
            - docker
            - gcloud
          resources:
            - admiralRepo
        setup:
          environmentVariables:
            normal:
              foo: bar
              boo: $foo
              shoo: foo boo
              moo: '"abc def"'
              zoo: '"\$a$foo"'
              koo: \(\)\$\\\!\@#%^*
              IMAGE_TAG: v7.2.4
            #secure:
            #  securefoo: qt/1lrsQSyC/ySCDr+19zmClURHst9PYEWLDVQVj8cjJxmTUWF1jrudBRbVZHH8/9fBAf2zPyFyQrQji0qBtESm+UjIzfDwr0I6kD+I89onVT2I/9Pq+RB3igEgJQB9Uycb1cxwTyvP6Kw1vH9ulVFb7DZBnc5Mngrmzv2iMPv9c2hv4tmltKWyGeB/UPIqqfadBrgj7lfimhIvr7tcHGG7XuLfI9yEf2hbaoqfPFWnIC8aoMrazkeyNuEUYCQzwy4l8YIOT06rFY5ajiDQkpKibePxMRGyF0QL0cdqU8guRxcEpfZNg/7/81SWkqlUiRMrf20jyVVdUxepac0dGKg==
          runtime:
            type: host
            #image:
            #  custom:
            #    name: drydock/u16microbase
            #    tag: $IMAGE_TAG
        execution:
          onExecute:
            - docker ps -a
            - echo $foo
            - echo $boo
            - echo $shoo
            - echo $moo
            - echo $zoo
            - echo $koo
            - echo $securefoo
            - printenv
            - cat $STEPLET_SCRIPT_PATH
            - echo $int_gcloud_jsonKey > test.json
            #- gcloud auth activate-service-account --key-file=test.json
            - sleep 1m
            - echo hi
            - sleep 1m
            - echo lol
            - sleep 1m
            - echo bye
      - name: build_reqproc_img
        type: bash
        setup:
          #environmentVariables:
          #  normal:
          #    boo: far
          #    choo: $abcd`@
          #  secure:
          #    bar: oPW1jPBkndpwxm8DwE8xfLF+jNzsdHU1gt+4bMRUCbcMgUa8BQto1hE9Tu2FIded8/2rCGxYIhrQDgiRg/zMn9raVT4DlHK7006gjoESeTPIq5KYsjYHn9VGr2dJ+jB9XXyLWb0pFSnRZCTrfL3P7qIqQw54yP9pTIw9Mqpzk5Juj1GCPgw6vag+SIIc3nd4ICt5BPIyQxMcP1UBKwnzIE0CAc/0JPnP9Lo0zvnzXZYFRSoAh08/jKL1rmtjMhb2WkPHGAfb6HnUgGyNBpN2HJO+jdG5tpXF94c3rB+ec6vMvMDuaoWL6ujrtPFq0AxxHMjzTQODNfVsxo8DzOk0jw==
          #    joo: CN7ZMONxXRBEBP0wMQ78LtNIVhjs+LWqFqLgVzUXU+R9FDnAGNvTSwtO8ym7d5pD+aZLcwO1BqX/pOqck1yTpCs/T5lWPvBw+Ivo66JgnEjAgrgtl9v4dy/CkLGaOw7t4QGMeTLu3NLTfxQSKtrulv3kHfp337l10QkbaWeUnUBU3570DCfpBt/zSJqt1ePeW9TuVaYvseX5JA+Y5CMQJqiDWwLznCmQo+NrOJ4zvBnDw5S3qnWw2zDxqjtZ2xVwR+/7+agM2oBGg/J7EAG2IxZCQFzODxVNk1gzH+YxXhcWAPB3bH8V/WajnglpAk5AmUrMMgWZnZbFesF4z0lBWQ==
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16microbase
                tag: master
                options: "-e optionfoo=bar "
        triggeredBy:
          resources:
            - reqproc_repo
        #    - gitrepo_res
        #requires:
        #  integrations:
      #      - docker
        outputResources:
          - reqproc_img
        execution:
          onStart:
            - echo "onStart"
          onExecute:
            #- echo 'hi'
            #- echo '!@!$#%$^%&%&^*&('
            #- echo $optionfoo
            #- echo "Hello World"
            - cat $STEPLET_SCRIPT_PATH
            #- echo yo
            #- echo $choo
            - echo $int_docker_password
            #- echo $readonlyfoo
            #- echo $bar
            #- echo $joo
            #- readonlyfoo=$foo
            - cat $STEP_JSON_PATH
            #- cat $STEP_JSON_PATH | jq .resources.gitrepo_res.configPropertyBag.shallowDepth
            #- cat $STEP_JSON_PATH | jq .resources.gitrepo_res.configPropertyBag.gitConfig
            - git config --list
            #- pushd $(cat $STEP_JSON_PATH | jq -r .resources.gitrepo_res.resourcePath)/gitRepo
            #- git log
            #- popd
          onComplete:
            - echo "onComplete"
          onSuccess:
            - echo "onSuccess"
          onFailure:
            - echo "onFailure"
      - name: push_reqproc_img
        type: bash
        setup:
          #environmentVariables:
          #  normal:
          #    boo: far
          #    choo: $abcd`@
          #  secure:
          #    bar: oPW1jPBkndpwxm8DwE8xfLF+jNzsdHU1gt+4bMRUCbcMgUa8BQto1hE9Tu2FIded8/2rCGxYIhrQDgiRg/zMn9raVT4DlHK7006gjoESeTPIq5KYsjYHn9VGr2dJ+jB9XXyLWb0pFSnRZCTrfL3P7qIqQw54yP9pTIw9Mqpzk5Juj1GCPgw6vag+SIIc3nd4ICt5BPIyQxMcP1UBKwnzIE0CAc/0JPnP9Lo0zvnzXZYFRSoAh08/jKL1rmtjMhb2WkPHGAfb6HnUgGyNBpN2HJO+jdG5tpXF94c3rB+ec6vMvMDuaoWL6ujrtPFq0AxxHMjzTQODNfVsxo8DzOk0jw==
          #    joo: CN7ZMONxXRBEBP0wMQ78LtNIVhjs+LWqFqLgVzUXU+R9FDnAGNvTSwtO8ym7d5pD+aZLcwO1BqX/pOqck1yTpCs/T5lWPvBw+Ivo66JgnEjAgrgtl9v4dy/CkLGaOw7t4QGMeTLu3NLTfxQSKtrulv3kHfp337l10QkbaWeUnUBU3570DCfpBt/zSJqt1ePeW9TuVaYvseX5JA+Y5CMQJqiDWwLznCmQo+NrOJ4zvBnDw5S3qnWw2zDxqjtZ2xVwR+/7+agM2oBGg/J7EAG2IxZCQFzODxVNk1gzH+YxXhcWAPB3bH8V/WajnglpAk5AmUrMMgWZnZbFesF4z0lBWQ==
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16microbase
                tag: master
                options: "-e optionfoo=bar"
        triggeredBy:
          resources:
            - reqproc_img
        execution:
          onExecute:
            - echo 'hi'
            
