jobs:  
  - name: nginx-manifest-trace_2
    type: manifest
    steps:
      - IN: nginx-image-trace_2
      - IN: trigger-trace_2

  - name: ddc-deploy-trace_2
    type: deploy
    steps:
      - IN: nginx-manifest-trace_2
      - IN: ddc-cluster-trace_2
      - IN: params-trace_2
      - TASK: managed

  - name: runSh-trace_copy
    type: runSh
    steps:
      - IN: sample_java-gitRepo_copy
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 3
    on_success:
      - script: echo "successfully completed"

#  - name: sample_java_runCI
#    type: runCI
#    steps:
#      - IN: runSh-trace_copy
#      - OUT: nginx-image-trace
