resources:
   - name: sample_node_repo_test
     type: gitRepo
     integrationName: github-subint
     repoPath: ankul-shippable/sample_node
     configuration:
        branches:
           except: "*test"
           only: "master*"
        tags:
           except: none
           only: none   
        buildOnCommit: true
        buildOnPullRequest: false
        buildOnPullRequestClose: false
        buildOnRelease: true
        buildOnTagPush: false
        buildOnFileCommit: "*test2"
        shallowDepth: 2
        gitConfig: 
          - dont_know
          - dont_know_2
     initialVersion:
       sha: master

pipelines:
      - name: test_step_1
        type: runSh
        # used to control steps that need to execute within a VM context
        configuration:
          affinityGroup: bldGroup 
          priority: 1
          timeoutSeconds: 6000000
          cache: true
        setup:
          environmentVariables:
            normal:
              - ENV1: value1
              - ENV2: value2
            encrypted:
              - SECURE_ENV1: <encrypted secure env value>
              - SECURE_ENV2: <encrypted secure env value>
          runtime: <image/host>
          image: repo
            auto:
              language: c#
              versions: latest
            custom:
              name: repo/img
              tag: latest
              options: none
        requires:
          integrations:
            - github-subint
      
        triggeredBy:
          resources:
            - sample_node_repo_test
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
