resources:
  - name: gitrepo_res
    type: gitRepo
    repoPath: jatindogra/sample_java
    configuration:
      integrationName: github
    initialVersion:
      sha: master

pipelines:
  - name: pipe_1
    setup:
      runtime: onHost
    steps:
      - name: step1_A
        type: bash
        configuration:
          affinityGroup: test_group 
        setup:
          runtime: onHost
        triggeredBy:
          resources:
            - gitrepo_res 
        execution:
          onExecute:
            - echo "executing step1_A..."
