language: java

jdk:
  - openjdk7
  - openjdk8 
  - openjdk9  
  - oraclejdk8
  - oraclejdk9

build:
  pre_ci:
    - echo 'true'
  pre_ci_boot:
    image_name: drydock/u14javall
    image_tag: master
    pull: true
    options: '--privileged=true --net=bridge -e FOO=true -e BOO=false'
    
  ci:
    - echo "lang c"
    - printenv
    - java -version    
    - nvm ls
    - echo "nvm ls done"
    - javac MyClass.java
    - java MyClass

      
jobs:
  - name: java_u16javall_Test
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: sample_java
      - TASK:
          name: version_openjdk7
          runtime:
            options:
              imageName: "drydock/u16javall"
              imageTag: "master"
          script:
            - update-alternatives --set java /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
            - java -version
            - cd $SAMPLE_JAVA_STATE && javac MyClass.java
            - cd $SAMPLE_JAVA_STATE && java MyClass
      - TASK:
          name: version_openjdk8
          runtime:
            options:
              imageName: "drydock/u16javall"
              imageTag: "master"
          script:
            - update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
            - java -version
            - cd $SAMPLE_JAVA_STATE && javac MyClass.java
            - cd $SAMPLE_JAVA_STATE && java MyClass    
      - TASK:
          name: version_openjdk9
          runtime:
            options:
              imageName: "drydock/u16javall"
              imageTag: "master"
          script:
            - update-alternatives --set java /usr/lib/jvm/java-9-openjdk-amd64/bin/java
            - java -version
            - cd $SAMPLE_JAVA_STATE && javac MyClass.java
            - cd $SAMPLE_JAVA_STATE && java MyClass
      - TASK:
          name: version_oraclejdk8
          runtime:
            options:
              imageName: "drydock/u16javall"
              imageTag: "master"
          script:
            - update-alternatives --set java /usr/lib/jvm/java-8-oracle/jre/bin/java
            - java -version
            - cd $SAMPLE_JAVA_STATE && javac MyClass.java
            - cd $SAMPLE_JAVA_STATE && java MyClass         
      - TASK:
          name: version_oraclejdk9
          runtime:
            options:
              imageName: "drydock/u16javall"
              imageTag: "master"
          script:
            - update-alternatives --set java  /usr/lib/jvm/java-9-oracle/bin/java 
            - java -version
            - cd $SAMPLE_JAVA_STATE && javac MyClass.java
            - cd $SAMPLE_JAVA_STATE && java MyClass                     

resources:
  - name: sample_java
    type: gitRepo
    integration: "github-subint"
    versionTemplate:
      sourceName: ankul-shippable/sample_java
      branch: u16javall
      
