jobs:
  - name: runSh-Job-java
    type: runSh
    steps:
      - IN: sample_java_runCI
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 3
    on_success:
      - script: echo "successfully completed"

  - name: sample_java_runCI
    type: runCI
    steps:
      - IN: runSh-Job-java
      - OUT: nginx-image-java

  - name: sample_pipelines_runCI
    type: runCI
    steps:
      - IN: sample_java_runCI
