resources:
  - name: gitrepo_res
    type: gitRepo
    repoPath: bharath92/samplePyt
    configuration:
      integrationName: github
    initialVersion:
      sha: master

pipelines:
  - name: pipe_1
    setup:
      runtime:
        type: image
        image:
          custom:
            name: drydock/u16microbase
            tag: v7.2.4
      
    steps:
      - name: step1_A
        type: bash
        configuration:
          affinityGroup: test_group 
        setup:
          environmentVariables:
            normal:
              boo: far
              choo: $abcd`@
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16all
                tag: master
                options: "-e foo=bar"
        #triggeredBy:
        #  resources:
        #    - gitrepo_res
        requires:
          integrations:
            - docker
        execution:
          onStart:
            - echo "onStart"
          onExecute:
            - echo "Hello World"
            - cat $STEPLET_SCRIPT_PATH
            - echo yo
            - echo $choo
          onComplete:
            - echo "onComplete"
          onSuccess:
            - echo "onSuccess"
          onFailure:
            - echo "onFailure"
