resources:
  - name: gitrepo_res
    type: gitRepo
    repoPath: bharath92/samplePyt
    configuration:
      integrationName: github
    initialVersion:
      sha: master

pipelines:
  - name: pipe_1
    setup:
      runtime:
        type: image
        image:
          custom:
            name: drydock/u16microbase
            tag: v7.2.4
      
    steps:
      - name: step1_A
        type: bash
        configuration:
          affinityGroup: test_group 
        setup:
          runtime:
            type: image
            auto:
              language: java
        triggeredBy:
          resources:
            - gitrepo_res
        requires:
          integrations:
            - github
        execution:
          onStart:
            - echo "onStart"
          onExecute:
            - echo "Hello World"
            - cat $STEPLET_SCRIPT_PATH
            - echo yo
          onComplete:
            - echo "onComplete"
          onSuccess:
            - echo "onSuccess"
          onFailure:
            - echo "onFailure"
